#  docker run --name rocketseat-nodejs-03-api-solid -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql:latest
version: '3'

services:
    rocketseat-nodejs-03-api-solid:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment:
        - POSTGRESQL_USERNAME=docker
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=apisolid
